dist: xenial
sudo: false
language: go
go:
- '1.11.4'
before_script:
- wget https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
- export PROTOC_DIR=/tmp/proto
- mkdir -p $PROTOC_DIR
- unzip protoc-3.6.1-linux-x86_64.zip -d $PROTOC_DIR
- chmod +x $PROTOC_DIR/bin/protoc
- export GO111MODULE=on

script:
  - go version
  - go mod download
  - make

before_deploy:
- rm protoc-gen-state
- export VER=`echo $TRAVIS_TAG|tr -d v`
- GOOS=darwin GOARCH=amd64 go build ./ && zip rotoc-gen-state-$VER-darwin-x86_64.zip protoc-gen-state state/options.proto && sha256sum protoc-gen-state-$VER-darwin-x86_64.zip > protoc-gen-state-$VER-darwin-x86_64.sum
- GOOS=linux GOARCH=amd64 go build ./ && zip rotoc-gen-state-$VER-linux-x86_64.zip protoc-gen-state state/options.proto && sha256sum protoc-gen-state-$VER-linux-x86_64.zip > protoc-gen-state-$VER-linux-x86_64.sum
- GOOS=windows GOARCH=amd64 go build ./ && zip rotoc-gen-state-$VER-windows-x86_64.zip protoc-gen-state state/options.proto && sha256sum protoc-gen-state-$VER-windowes-x86_64.zip > protoc-gen-state-$VER-windowes-x86_64.sum
- ls -l
deploy:
  provider: releases
  api_key:
    secure: U7lFeXaWvvF5Ehz54ZyOta9m8cDZ7pYxFhnj/9qNfcnu58v4YIoEUbBb84Zkjsx9kW9Qb9lQ3nGs3I4nIi5OM+f10C4XlSDAVXWurQDCBY/OfvnvZrlhtcJPZzwn3R6dyLhz1mBU4VEahSb7WqOKsJ3JD/zaH5f8dOPenG2HAgjfsvuAxjk7qUQsp7g0auemeigG0WeREIw1vj2ziGconLXecsA/0YBOWuxuq7JryRHAqIC78AI/r2/ZsNWL27/M++7x1auR1uJ5weHdLfE1bYbCZWI1XrAgh7d02V6mT10dbVfESyV7N400ULz4DXSEZL3Z8f0T2LMcNcaAnXrqp4ifiVtejKAjbCFeIvWvPv2usMgtfPYLr0DOuxuLkk8mdE+6mK0nhGmaHaIUm4lEqiKTBWhzrR4sNxsUCb1uGe9ke2nkG2SnhkXGRPTnPV2MlwWrHtqKVX2PMw6BMDJcyD7MAf2KN2V6sF3C4tgN0C0OYpv5y6A7TQaFZs0VFJVEVCVJH7ahC341K++mYN1B7jSDE1ez6loXWzBJoyjzR7Cfbt5K6Ey9emY8k9upoIaVfKedhlBJbj+FnEZnmExsn2fb/uIInpLIk6pKOaHaReZbgY7OGzGC+pcACQS8iVxriB3OpdPibLIRTGjIEaJtqQ+qU3h3L566D8USFwF/mnQ=
  file_glob: true
  file:
    - protoc-gen-state-*.zip
    - protoc-gen-state-*.sum
  skip_cleanup: true
  on:
    tags: true
